# Generated by Django 3.0.3 on 2020-03-16 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmodel',
            name='planet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruit.PlanetModel'),
        ),
        migrations.AlterField(
            model_name='sithmodel',
            name='learnPlanet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruit.PlanetModel'),
        ),
    ]
