# Generated by Django 3.0.3 on 2020-03-16 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0002_auto_20200316_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueOrdenNumberModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueTestNumber', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='testtask',
            name='question',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='testtask',
            name='uniqueOrdenNumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruit.UniqueOrdenNumberModel'),
        ),
    ]
