# Generated by Django 3.0.3 on 2020-03-16 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0003_auto_20200316_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitAnswerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField(default=False)),
                ('quetion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruit.TestTask')),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.RecruitModel')),
            ],
        ),
    ]
