# Generated by Django 3.0.3 on 2020-03-18 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0004_recruitanswermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmodel',
            name='handOfShadow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruit.SithModel'),
        ),
    ]
